// import './bases/const-let';
// import './bases/template-strings';
// import './bases/literal-objects';
// import './bases/arrays';
// import './bases/functions';
// import './bases/destructuring-objects';
// import './bases/destructuring-arrays';
// import './bases/import-export-files';
// import './bases/promises';
// import './bases/fetch-api';
// import './bases/async-await';
import './bases/ternary-conditional';